const avatarWidth = 300;
const avatarHeight = 400;

const getRandomAvatarImage = () => {
  const randomNumber = Math.floor(Math.random() * 1000);
  return `https://picsum.photos/id/${randomNumber}/${avatarWidth}/${avatarHeight}`;
};

export const Products = [
  {
    id: 1,
    productName: 'Classic Suit',
    companyName: 'ElegantWear',
    productPrice: 399.99,
    productRating: 4.7,
    quantity: 1,
    productImage:  '/assets/images/products/n8.jpg',
    description: 'Indulge in timeless elegance with our Classic Suit from ElegantWear. Meticulously crafted for formal occasions, this suit effortlessly combines sophistication and style. Its impeccable tailoring ensures a flawless fit, while the premium fabric exudes luxury. Elevate your presence at special events with this iconic ensemble that resonates with refined taste.',
  },
  {
    id: 2,
    productName: 'Casual Blazer',
    companyName: 'UrbanChic',
    productPrice: 129.99,
    productRating: 4.4,
    quantity: 1,
    productImage: '/assets/images/products/f2.jpg',
    description: 'Step into effortless style with our Casual Blazer from UrbanChic. This versatile blazer is designed for everyday wear, adding a touch of sophistication to your look. The tailored fit and contemporary design make it suitable for both work and leisure, allowing you to make a statement wherever you go.',
  },
  {
    id: 3,
    productName: 'Denim Jacket',
    companyName: 'VintageDenim',
    productPrice: 89.99,
    productRating: 4.2,
    quantity: 1,
    productImage: '/assets/images/products/n7.jpg',
    description: 'Embrace timeless style with our Denim Jacket from VintageDenim. This classic piece brings a touch of vintage charm to your wardrobe. Crafted with care, the denim jacket features a versatile design suitable for various occasions. Whether you\'re strolling through the city or enjoying a cool evening, this jacket adds a dash of nostalgia to your look.',
  },
  {
    id: 4,
    productName: 'Formal Tuxedo',
    companyName: 'BlackTieAffair',
    productPrice: 599.99,
    productRating: 4.9,
    quantity: 1,
    productImage: '/assets/images/products/n6.jpg',
    description: 'Radiate sophistication at black tie events with our Formal Tuxedo from BlackTieAffair. This exquisite tuxedo is designed to command attention, exuding timeless elegance. The meticulous craftsmanship ensures a perfect fit, while the premium materials reflect the pinnacle of luxury. Make a lasting impression with this symbol of refined style.',
  },
  {
    id: 5,
    productName: 'Leather Jacket',
    companyName: 'RuggedStyle',
    productPrice: 249.99,
    productRating: 4.6,
    quantity: 1,
    productImage: '/assets/images/products/n5.jpg',
    description: 'Embrace rebellion with our Leather Jacket from RuggedStyle. This rugged yet refined jacket boasts distinctive style and durability. Crafted from premium leather, it exudes a sense of adventure and edge. Whether you\'re exploring the city streets or heading out for a night with friends, this jacket is your ticket to confident style.',
  },
  {
    id: 6,
    productName: 'Summer Shorts',
    companyName: 'BeachVibes',
    productPrice: 59.99,
    productRating: 4.3,
    quantity: 1,
    productImage: '/assets/images/products/n4.jpg',
    description: 'Embrace the spirit of summer with our Summer Shorts from BeachVibes. Designed for comfort and style, these shorts are perfect for warm-weather adventures. The breathable fabric and modern design make them ideal for beach outings, picnics, and casual hangouts. Stay cool and fashionable with these essential summer companions.',
  },
  {
    id: 7,
    productName: 'Vintage Dress',
    companyName: 'RetroChic',
    productPrice: 149.99,
    productRating: 4.5,
    quantity: 1,
    productImage: '/assets/images/products/n3.jpg',
    description: 'Step into the past with our Vintage Dress from RetroChic. This enchanting dress captures the essence of bygone eras, bringing retro charm to your wardrobe. The intricate details and timeless design make it perfect for special occasions and memorable moments. Make a statement with this piece of wearable nostalgia.',
  },
  {
    id: 8,
    productName: 'Sports Sneakers',
    companyName: 'ActiveGear',
    productPrice: 79.99,
    productRating: 4.2,
    quantity: 1,
    productImage: '/assets/images/products/f8.jpg',
    description: 'Elevate your performance with our Sports Sneakers from ActiveGear. Engineered for active lifestyles, these sneakers offer comfort, support, and style. Whether you\'re hitting the gym, going for a run, or simply staying on your feet, these sneakers are your reliable companion for every step of the journey.',
  },
  {
    id: 9,
    productName: 'Printed T-shirt',
    companyName: 'GraphicRevolution',
    productPrice: 29.99,
    productRating: 4.0,
    quantity: 1,
    productImage: '/assets/images/products/n4.jpg',
    description: 'Express your individuality with our Printed T-shirt from GraphicRevolution. This trendy t-shirt showcases unique graphics that make a statement. Crafted with care, the high-quality fabric ensures comfort and durability. Whether you\'re attending events or exploring the city, let your style speak volumes with this versatile piece.',
  },
  {
    id: 10,
    productName: 'Floral Skirt',
    companyName: 'BlossomBoutique',
    productPrice: 49.99,
    productRating: 4.6,
    quantity: 1,
    productImage: '/assets/images/products/n3.jpg',
    description: 'Elevate your femininity with our Floral Skirt from BlossomBoutique. This charming skirt adds a touch of elegance to your wardrobe, perfect for various occasions. The delicate floral pattern and flowing design exude grace and charm. Whether you\'re attending gatherings or enjoying a leisurely day, this skirt is a must-have for timeless style.',
  },
  {
    id: 11,
    productName: 'Casual Jeans',
    companyName: 'DenimDaze',
    productPrice: 69.99,
    productRating: 4.3,
    quantity: 1,
    productImage: '/assets/images/products/n2.jpg',
    description: 'Experience comfort and style with our Casual Jeans from DenimDaze. These versatile jeans are designed for everyday wear, offering a perfect blend of comfort and fashion. Crafted with attention to detail, the classic design makes them suitable for various occasions. Whether you\'re running errands or meeting friends, these jeans are your go-to choice.',
  },
  {
    id: 12,
    productName: 'Formal Dress',
    companyName: 'ElegantAffair',
    productPrice: 299.99,
    productRating: 4.8,
    quantity: 1,
    productImage: '/assets/images/products/n1.jpg',
    description: 'Radiate elegance at special occasions with our Formal Dress from ElegantAffair. Designed to captivate attention, this dress exudes sophistication and grace. The exquisite details and luxurious fabric make it a true masterpiece. Whether you\'re attending galas or elegant gatherings, this dress ensures you stand out with timeless beauty.',
  },
  {
    id: 13,
    productName: 'Lounge Set',
    companyName: 'CozyComfort',
    productPrice: 89.99,
    productRating: 4.1,
    quantity: 1,
    productImage: '/assets/images/products/f8.jpg',
    description: 'Indulge in ultimate relaxation with our Lounge Set from CozyComfort. Unwind and pamper yourself in this comfortable ensemble, perfect for tranquil moments. The soft fabric and thoughtful design make it your ideal companion for leisurely evenings at home. Elevate your comfort with this cozy and stylish loungewear.',
  },
  {
    id: 14,
    productName: 'Active Leggings',
    companyName: 'FitnessFusion',
    productPrice: 49.99,
    productRating: 4.5,
    quantity: 1,
    productImage: '/assets/images/products/f7.jpg',
    description: 'Enhance your workouts with our Active Leggings from FitnessFusion. Designed for performance and style, these leggings offer optimal mobility and comfort. Whether you\'re hitting the gym or practicing yoga, the breathable fabric and supportive fit ensure a superior workout experience. Elevate your fitness journey with these essential leggings.',
  },
  {
    id: 15,
    productName: 'Designer Watch',
    companyName: 'LuxuryTimepieces',
    productPrice: 799.99,
    productRating: 4.9,
    quantity: 1,
    productImage: '/assets/images/products/f6.jpg',
    description: 'Elevate your wrist with our Designer Watch from LuxuryTimepieces. This luxurious timepiece embodies timeless style and sophistication. Crafted with precision, the exquisite details and elegant design make it a symbol of refined taste. Whether you\'re attending formal events or everyday affairs, this watch completes your look with grace.',
  },
  {
    id: 16,
    productName: 'Formal Shoes',
    companyName: 'DapperFootwear',
    productPrice: 159.99,
    productRating: 4.7,
    quantity: 1,
    productImage: '/assets/images/products/f5.jpg',
    description: 'Step into elegance with our Formal Shoes from DapperFootwear. These sophisticated shoes are meticulously crafted for upscale occasions. The premium materials and impeccable design ensure a confident stride. Whether you\'re attending weddings or business meetings, these shoes elevate your look with timeless grace.',
  },
  {
    id: 17,
    productName: 'Stylish Hat',
    companyName: 'FashionFusion',
    productPrice: 39.99,
    productRating: 4.3,
    quantity: 1,
    productImage: '/assets/images/products/f4.jpg',
    description: 'Elevate your fashion game with our Stylish Hat from FashionFusion. This trendy accessory adds a touch of flair to your outfits, making a statement wherever you go. Crafted with attention to detail, the versatile design complements various styles. Whether you\'re strolling through the city or attending events, this hat is your style companion.',
  },
  {
    id: 18,
    productName: 'Travel Backpack',
    companyName: 'AdventureEssentials',
    productPrice: 129.99,
    productRating: 4.6,
    quantity: 1,
    productImage: '/assets/images/products/f3.jpg',
    description: 'Embark on journeys with confidence using our Travel Backpack from AdventureEssentials. This durable and spacious backpack is designed to be your reliable companion on all your adventures. The thoughtful features and comfortable design make it perfect for travelers and explorers alike. Pack your essentials and embrace the thrill of discovery.',
  },
  {
    id: 19,
    productName: 'Designer Sunglasses',
    companyName: 'SunshineStyle',
    productPrice: 199.99,
    productRating: 4.8,
    quantity: 1,
    productImage: '/assets/images/products/f2.jpg',
    description: 'Shield your eyes in style with our Designer Sunglasses from SunshineStyle. These chic sunglasses combine fashion and functionality, protecting your eyes with elegance. Crafted with attention to detail, the luxurious design exudes sophistication. Whether you\'re lounging by the pool or strolling along the beach, these sunglasses complete your look.',
  },
  {
    id: 20,
    productName: 'Casual Hoodie',
    companyName: 'CozyComfort',
    productPrice: 79.99,
    productRating: 4.4,
    quantity: 1,
    productImage: '/assets/images/products/f1.jpg',
    description: 'Wrap yourself in comfort with our Casual Hoodie from CozyComfort. This versatile hoodie is your go-to choice for casual and cozy days. The soft fabric and relaxed fit ensure a snug feeling, perfect for lounging or running errands. Whether you\'re indoors or outdoors, embrace relaxation and warmth with this essential wardrobe piece.',
  },
];

